name: Create branch on new tag in finschia

on:
  push:
  pull_request:
  release:
  deployment:

jobs:
  create-bump-up-PR:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install -g prettier
